# Process-compose based test environment for the registry server.
# This module provides a process-compose configuration for running
# the registry server with mocked external services for local development
# and testing.
#
# Usage:
#   nix run .#test-env                    # Start with log streaming (default)
#   nix run .#test-env -- --tui           # Start with interactive TUI
#   nix run .#test-env -- --detached      # Run detached (background)
#
# All arguments are passed directly to process-compose. See `process-compose --help`.
#
# When detached, manage with:
#   process-compose -p 9006 attach        # Attach TUI to running instance
#   process-compose -p 9006 down          # Stop all services
#
# Environment variables:
#   STATE_DIR     - Override the state directory (default: temp dir, cleaned on exit)
#   SERVER_PORT   - Exported automatically for E2E tests to discover the server
{
  pkgs,
  lib,
  rootPath,
}:
let
  testConfig = import ./config.nix {
    inherit
      pkgs
      lib
      rootPath
      ;
  };

  inherit (testConfig)
    ports
    combinedWiremockRoot
    serverStartScript
    publishPayload
    ;

  mkWiremockProcess = name: port: {
    command = "${pkgs.wiremock}/bin/wiremock --port ${toString port} --root-dir ${combinedWiremockRoot}/${name} --disable-banner";
    readiness_probe = {
      http_get = {
        host = "127.0.0.1";
        inherit port;
        path = "/__admin";
      };
      initial_delay_seconds = 1;
      period_seconds = 1;
    };
    shutdown = {
      signal = 15;
      timeout_seconds = 5;
    };
  };

  processComposeConfig = {
    version = "0.5";
    processes = {
      wiremock-github = mkWiremockProcess "github" ports.github;
      # Unified storage WireMock instance for S3 + bucket + Pursuit with stateful scenarios
      wiremock-storage = mkWiremockProcess "storage" ports.storage;
      wiremock-healthchecks = mkWiremockProcess "healthchecks" ports.healthchecks;

      registry-server = {
        command = "${serverStartScript}/bin/start-server";
        depends_on = {
          wiremock-github.condition = "process_healthy";
          wiremock-storage.condition = "process_healthy";
          wiremock-healthchecks.condition = "process_healthy";
        };
        readiness_probe = {
          http_get = {
            host = "127.0.0.1";
            port = ports.server;
            path = "/api/v1/jobs";
          };
          initial_delay_seconds = 2;
          period_seconds = 1;
        };
        shutdown = {
          signal = 15;
          timeout_seconds = 5;
        };
      };
    };
  };

  processComposeYaml = pkgs.writeText "process-compose.yaml" (builtins.toJSON processComposeConfig);

  testEnvExports = testConfig.envToExports testConfig.testEnv;

  # Generate echo statements that write export lines to a file
  testEnvFileExports = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (name: value: ''echo 'export ${name}="${value}"' '') testConfig.testEnv
  );

  testEnvScript = pkgs.writeShellScriptBin "test-env" ''
    set -e

    # Export test environment variables for E2E test runners
    ${testEnvExports}

    if [ -z "''${STATE_DIR:-}" ]; then
      STATE_DIR="$(mktemp -d)"
      export STATE_DIR
      echo "Using temporary STATE_DIR: $STATE_DIR"
      trap 'echo "Cleaning up $STATE_DIR..."; rm -rf "$STATE_DIR"' EXIT
    else
      export STATE_DIR
      echo "Using existing STATE_DIR: $STATE_DIR"
    fi

    mkdir -p "$STATE_DIR"

    # Derived paths needed by server and E2E tests
    export REPO_FIXTURES_DIR="$STATE_DIR/repo-fixtures"

    # Write a shareable env file so other terminals can join the same test env
    SHARED_ENV_FILE="$STATE_DIR/test-env.sh"
    {
      echo "#!/usr/bin/env bash"
      echo "# Generated by: nix run .#test-env"
      echo "# Shared test environment for registry e2e tests"
      echo
      echo "export STATE_DIR=\"$STATE_DIR\""
      echo "export REPO_FIXTURES_DIR=\"$REPO_FIXTURES_DIR\""
      ${testEnvFileExports}
    } > "$SHARED_ENV_FILE"
    chmod +x "$SHARED_ENV_FILE"

    # Create a symlink at a predictable location so TUI users can find the env file
    rm -f test-env-link 2>/dev/null || true
    ln -sf "$STATE_DIR" test-env-link

    echo
    echo "[test-env] Environment exports written to: $SHARED_ENV_FILE"
    echo "[test-env] Symlink created: ./test-env-link -> $STATE_DIR"
    echo "[test-env] In another terminal, run:"
    echo "  source test-env-link/test-env.sh"
    echo "  spago run -p registry-app-e2e"
    echo

    exec ${pkgs.process-compose}/bin/process-compose up \
      -f ${processComposeYaml} \
      --ordered-shutdown \
      -t=false \
      "$@"
  '';

in
{
  inherit
    testEnvScript
    processComposeYaml
    publishPayload
    ports
    ;

  # Re-export commonly-used items from testConfig for convenience.
  # This avoids verbose paths like `testEnv.testConfig.wiremockStartScript`.
  inherit (testConfig)
    wiremockStartScript
    serverStartScript
    setupGitFixtures
    testEnv
    envToExports
    ;

  # Full testConfig still available for less common access patterns
  inherit testConfig;
}
